---
driver:
  name: vagrant
  provider: parallels

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.7
    driver:
      box: parallels/centos-6.7

suites:
  - name: default
    run_list:
      - recipe[lwrp_test::default]
    attributes:
