settings:
  parallel: true

driver:
  name: docker

platforms:
- name: centos-6
  driver:
    image: centos:6
    platform: rhel

- name: debian-7
  driver:
    image: debian:7
    platform: debian
    provision_command:
      - /usr/bin/apt-get update

- name: ubuntu-14.04
  driver:
    image: ubuntu:14.04
    platform: ubuntu
    provision_command:
      - /usr/bin/apt-get update

provisioner:
  name: chef_zero

suites:
  - name: default
    run_list:
      - recipe[lwrp_test::default]
